# Generated by Django 6.1 on 2026-08-21 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_bulkrequirement_farmeroffer_preharvestcontract'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='product_subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_charge',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
