# Generated by Django 6.1 on 2026-08-22 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_product_subtotal_order_shipping_charge'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cancellation_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='cancellation_locked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
