# Generated by Django 6.0.1 on 2026-08-22 06:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_cancellation_locked_and_more'),
        ('products', '0003_auction_bid_flashsale_grouporder_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.CharField(choices=[('weekly', 'Weekly'), ('biweekly', 'Bi-Weekly'), ('daily', 'Daily')], default='weekly', max_length=20)),
                ('delivery_day', models.CharField(default='Monday', max_length=20)),
                ('delivery_time_slot', models.CharField(choices=[('morning', 'Morning (6:00 AM - 9:00 AM)'), ('afternoon', 'Afternoon (12:00 PM - 3:00 PM)'), ('evening', 'Evening (5:00 PM - 8:00 PM)')], default='morning', max_length=20)),
                ('duration_months', models.IntegerField(default=2)),
                ('total_deliveries', models.IntegerField(default=8)),
                ('completed_deliveries', models.IntegerField(default=0)),
                ('start_date', models.DateField()),
                ('next_delivery_date', models.DateField()),
                ('shipping_address', models.TextField()),
                ('shipping_pincode', models.CharField(max_length=10)),
                ('per_delivery_subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=5.0, max_digits=5)),
                ('shipping_charge', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('per_delivery_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_plan_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='active', max_length=20)),
                ('razorpay_subscription_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='orders.subscription'),
        ),
        migrations.CreateModel(
            name='SubscriptionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.subscription')),
            ],
        ),
    ]
