# Generated by Django 6.0.1 on 2026-08-22 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_subscription_order_subscription_subscriptionitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='per_delivery_discount',
            new_name='subscriber_discount',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='per_delivery_shipping',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='start_date',
        ),
        migrations.AlterField(
            model_name='order',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_orders', to='orders.subscription'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='completed_deliveries',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='delivery_day',
            field=models.CharField(default='Monday', max_length=20),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='delivery_time_slot',
            field=models.CharField(default='morning', max_length=20),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='duration_months',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='total_deliveries',
            field=models.IntegerField(default=8),
        ),
    ]
