# Generated by Django 6.0.1 on 2026-08-22 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_subscription_order_subscription_subscriptionitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='delivery_day',
            field=models.CharField(default='Monday', max_length=150),
        ),
    ]
