# Generated by Django 6.1 on 2026-08-22 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_subscription_delivery_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='delivery_day',
            field=models.CharField(default='Monday', max_length=20),
        ),
    ]
