# Generated by Django 6.1 on 2026-08-22 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_subscription_model'),
        ('orders', '0008_alter_subscription_delivery_day'),
    ]

    operations = [
    ]
