# Generated by Django 6.1 on 2026-08-22 14:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_merge_20260822_1935'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='subscriber_discount',
        ),
        migrations.AddField(
            model_name='subscription',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='subscription',
            name='frequency',
            field=models.CharField(choices=[('weekly', 'Weekly'), ('biweekly', 'Bi-Weekly'), ('daily', 'Daily')], default='weekly', max_length=20),
        ),
        migrations.AddField(
            model_name='subscription',
            name='razorpay_subscription_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='shipping_charge',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='subscription',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='orders.subscription'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='delivery_time_slot',
            field=models.CharField(choices=[('morning', 'Morning (6:00 AM - 9:00 AM)'), ('afternoon', 'Afternoon (12:00 PM - 3:00 PM)'), ('evening', 'Evening (5:00 PM - 8:00 PM)')], default='morning', max_length=20),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='next_delivery_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='active', max_length=20),
        ),
    ]
