# Generated by Django 6.1 on 2026-09-16 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_remove_subscription_subscriber_discount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cancellation_reason',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
