# Generated by Django 6.1 on 2026-09-19 22:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_order_cancellation_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmeroffer',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='farmer_offers', to='orders.order'),
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quote_requests', to='orders.order'),
        ),
    ]
