# Generated by Django 6.1 on 2026-08-22 10:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar_url', models.URLField(blank=True, default='', max_length=500)),
                ('full_name', models.CharField(blank=True, default='', max_length=200)),
                ('alternate_whatsapp', models.CharField(blank=True, default='', max_length=15)),
                ('village', models.CharField(blank=True, default='', max_length=100)),
                ('taluka', models.CharField(blank=True, default='', max_length=100)),
                ('state', models.CharField(blank=True, default='', max_length=100)),
                ('farm_size_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('farm_size_unit', models.CharField(choices=[('acres', 'Acres'), ('bigha', 'Bigha'), ('hectares', 'Hectares')], default='acres', max_length=20)),
                ('soil_farming_type', models.CharField(choices=[('organic', 'Organic'), ('natural', 'Natural'), ('conventional', 'Conventional'), ('mixed', 'Mixed')], default='conventional', max_length=20)),
                ('trust_score', models.IntegerField(default=0)),
                ('total_trips', models.IntegerField(default=0)),
                ('ontime_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('avg_rating', models.DecimalField(decimal_places=1, default=0, max_digits=3)),
                ('primary_crops', models.JSONField(blank=True, default=list)),
                ('production_seasons', models.JSONField(blank=True, default=list)),
                ('irrigation_source', models.CharField(choices=[('drip', 'Drip Irrigation'), ('canal', 'Canal'), ('well', 'Well / Borewell'), ('rainfed', 'Rainfed'), ('sprinkler', 'Sprinkler')], default='well', max_length=20)),
                ('bank_account_name', models.CharField(blank=True, default='', max_length=200)),
                ('bank_account_number', models.CharField(blank=True, default='', max_length=30)),
                ('ifsc_code', models.CharField(blank=True, default='', max_length=20)),
                ('upi_id', models.CharField(blank=True, default='', max_length=100)),
                ('govt_id_type', models.CharField(choices=[('aadhaar', 'Aadhaar Card'), ('kcc', 'Kisan Credit Card'), ('pmkisan', 'PM-Kisan ID'), ('voter', 'Voter ID')], default='aadhaar', max_length=20)),
                ('govt_id_number', models.CharField(blank=True, default='', max_length=30)),
                ('govt_id_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='farmer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Farmer Profile',
                'verbose_name_plural': 'Farmer Profiles',
            },
        ),
    ]
