# Generated by Django 6.1 on 2026-09-16 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer_profile', '0002_farmerprofile_avg_freshness_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmerprofile',
            name='farm_lands',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
