# Generated by Django 6.1 on 2026-09-16 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auction_bid_flashsale_grouporder_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stored_in_cold_storage',
            field=models.BooleanField(default=False),
        ),
    ]
