# Generated by Django 6.1 on 2026-09-16 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_stored_in_cold_storage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='source_land',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
