# Generated by Django 6.1 on 2026-08-22 07:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('logistics', '0005_deliveryshipment_destination_lat_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RoutePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_version', models.IntegerField(default=1)),
                ('route_geometry', models.JSONField(default=list)),
                ('candidate_routes', models.JSONField(default=list)),
                ('distance_km', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('duration_minutes', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('estimated_departure', models.DateTimeField(blank=True, null=True)),
                ('estimated_arrival', models.DateTimeField(blank=True, null=True)),
                ('weather_risk', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=10)),
                ('quality_risk', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=10)),
                ('weather_snapshot', models.JSONField(default=list)),
                ('commodity_sop_data', models.JSONField(default=dict)),
                ('selection_method', models.CharField(choices=[('llm_recommendation', 'LLM Recommendation'), ('deterministic_fallback', 'Deterministic Fallback'), ('operator_override', 'Operator Override')], default='deterministic_fallback', max_length=30)),
                ('llm_reason', models.TextField(blank=True, null=True)),
                ('llm_confidence', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(choices=[('GENERATED', 'Generated'), ('ANALYZING', 'Analyzing'), ('RECOMMENDED', 'Recommended'), ('AWAITING_CONFIRMATION', 'Awaiting Confirmation'), ('CONFIRMED', 'Confirmed'), ('ACTIVE', 'Active'), ('RECALCULATION_REQUIRED', 'Recalculation Required'), ('SUPERSEDED', 'Superseded'), ('COMPLETED', 'Completed')], default='GENERATED', max_length=30)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_route_plans', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_route_plans', to=settings.AUTH_USER_MODEL)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_plans', to='logistics.deliveryshipment')),
            ],
            options={
                'ordering': ['-route_version'],
            },
        ),
        migrations.CreateModel(
            name='RouteAuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('GENERATED', 'Generated'), ('RECOMMENDED', 'Recommended'), ('CONFIRMED', 'Confirmed'), ('ACTIVATED', 'Activated'), ('RECALCULATED', 'Recalculated'), ('SUPERSEDED', 'Superseded'), ('COMPLETED', 'Completed'), ('ROUTE_CHANGE_REQUESTED', 'Route Change Requested'), ('LLM_FAILED', 'LLM Failed Fallback Used')], max_length=40)),
                ('route_version', models.IntegerField()),
                ('reason', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='route_audit_events', to=settings.AUTH_USER_MODEL)),
                ('route_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_events', to='route_planning.routeplan')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
