# Generated by Django 6.1 on 2026-09-03 12:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='chatmessage',
            new_name='chat_messag_convers_426894_idx',
            old_name='chat_messages_conversation_id_idx',
        ),
        migrations.RenameIndex(
            model_name='chatmessage',
            new_name='chat_messag_created_eb4133_idx',
            old_name='chat_messages_created_at_idx',
        ),
        migrations.RenameIndex(
            model_name='chatmessage',
            new_name='chat_messag_convers_0a903c_idx',
            old_name='chat_messages_conversation_created_idx',
        ),
        migrations.RenameIndex(
            model_name='conversation',
            new_name='conversatio_farmer__7c06cf_idx',
            old_name='conversations_farmer_id_idx',
        ),
        migrations.RenameIndex(
            model_name='conversation',
            new_name='conversatio_updated_8d1310_idx',
            old_name='conversations_updated_at_idx',
        ),
        migrations.RenameIndex(
            model_name='conversation',
            new_name='conversatio_farmer__e270aa_idx',
            old_name='conversations_farmer_updated_idx',
        ),
        migrations.RenameIndex(
            model_name='farmermemory',
            new_name='farmer_memo_farmer__3c93d2_idx',
            old_name='farmer_memories_farmer_id_idx',
        ),
        migrations.RenameIndex(
            model_name='farmermemory',
            new_name='farmer_memo_farmer__61e01b_idx',
            old_name='farmer_memories_farmer_key_idx',
        ),
        migrations.RenameIndex(
            model_name='toolcalllog',
            new_name='tool_call_l_convers_44e8e2_idx',
            old_name='tool_call_logs_conversation_id_idx',
        ),
        migrations.RenameIndex(
            model_name='toolcalllog',
            new_name='tool_call_l_created_cd788a_idx',
            old_name='tool_call_logs_created_at_idx',
        ),
        migrations.RenameIndex(
            model_name='toolcalllog',
            new_name='tool_call_l_tool_na_618057_idx',
            old_name='tool_call_logs_tool_name_idx',
        ),
        migrations.AddField(
            model_name='conversation',
            name='is_pinned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='conversation',
            name='pinned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='farmermemory',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='toolcalllog',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['farmer_id', 'is_pinned', 'pinned_at'], name='conversatio_farmer__b82c56_idx'),
        ),
    ]
