# Generated by Django 6.1 on 2026-08-22 01:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0003_deliveryshipment_delivery_otp_logisticspartner_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryshipment',
            name='handover_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deliveryshipment',
            name='handover_confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_handovers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='deliveryshipment',
            name='status',
            field=models.CharField(choices=[('assigned', 'Assigned'), ('picked_up', 'Picked Up'), ('handover_completed', 'Transport Handover Completed'), ('delivered', 'Delivered')], default='assigned', max_length=20),
        ),
    ]
