# Generated by Django 6.1 on 2026-09-16 09:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0005_deliveryshipment_destination_lat_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TransportOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transport_offers_sent', to=settings.AUTH_USER_MODEL)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transport_offers_received', to='logistics.logisticspartner')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transport_offers', to='logistics.deliveryshipment')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('shipment', 'partner'), name='unique_transport_offer_per_driver')],
            },
        ),
    ]
